apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: weather.local
    http:
      paths:
      - path: /weather
        pathType: Prefix
        backend:
          service:
            name: weather-api-svc
            port:
              number: 80
      - path: /notify
        pathType: Prefix
        backend:
          service:
            name: notify-service-svc
            port:
              number: 80

